server:
  port: 8083

spring:
  application:
    name: project
  datasource:
    url: jdbc:mysql://localhost:3306/project
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    org:
     hibernate:
      SQL: DEBUG

jwt:
  expiration:
    local: 86400000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/